version: 2

models:
  - name: dim_empresa
    description: "Dimensão de empresas, combinando cadastro, porte, enquadramento e dados da bolsa."
    columns:
      - name: sk_empresa
        tests: [not_null, unique]
      - name: cnpj
        tests: [not_null]

  - name: dim_tempo
    description: "Dimensão de tempo derivada das datas de pregão."
    columns:
      - name: data
        tests: [not_null, unique]

  - name: fato_cotacoes
    description: "Fato de cotações diárias de ações, ligando empresa e tempo."
    columns:
      - name: data
        tests: [not_null]
      - name: ticker
        tests: [not_null]
